### ISSUE TITLE
Highlight languages / filter by language

### ISSUE THREAD

**Issue by Standard8** [mozilla-frontend-infra/codetribute#100]
One of the benefits of bugsahoy was that you could filter by language (c++/js/etc). There's lots of people that don't know all languages, so it would help people when finding associated bugs.

codetribute could maybe just list the languages, and add a filter, or just do a filter.

I believe it is generally the mentored bugs that have been annotated in the past (not always the good-first-bugs). There are generally annotated in the whiteboard with one of:

```
[lang=js][lang=xul]
[lang=js,xul]
[lang=js/xul]
```

**Comment by fiennyangeln** [comment]
@Standard8 Yup! I just learned that some of the info are obtained from the whiteboard. I think getting the whiteboard field won't be hard, so we can parse and incorporate it with the tag of the bug obtained from the keyword. It will list the language and automatically add filter to the bugs. But it will only happen after the user select a project.

Do you think we should also handle filter by language before selecting a project? 
cc: @helfi92 @eliperelman @djmitche

**Comment by djmitche** [comment]
Yes, let's make it part of the filtering.
