### ISSUE TITLE
Better UX for the project introduction

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#179]
Having the project introduction closed by default is not optimal because it requires the user to do an extra click every time they navigate to a project to have a quick summary of the project. Instead, we should be able to show the first section of the markdown and have a "See more" or "..." button that expands the introduction and a "Show less" button when the introduction is expanded.

To implement this, you could perhaps take the markdown content and take everything up until the second `<h2>` element. Once the user clicks on "See more", we can show the rest.

**Comment by helfi92** [comment]
@fiennyangeln How is this one coming along? Is there anything I can help you with?

**Comment by fiennyangeln** [comment]
Still trying to do the separation using Regex before it turned into DOM nodes.. Or is it possible to do it on DOM nodes?

**Comment by helfi92** [comment]
What do you mean by "before it turned into DOM nodes"? Are you able to console log the full content of the project introduction?

**Comment by fiennyangeln** [comment]
Yup! its all the markdown in a string format like 

## H2 Title \n h2 entry ## Another H2 title \n h2 entry h2 entry ### H3 title \n  H3 entry

**Comment by helfi92** [comment]
Have you tried something like `markdownContent.split('##')[1]`? This should give you the first paragraph. At load time, we can display that and then once the user clicks on "Show More", we render the initial markdown content.

**Comment by fiennyangeln** [comment]
Ok

**Comment by helfi92** [comment]
@vaishnavipamulapati This would be a fun task to work on. Happy to help along the way :) Let me know if you're interested.

**Comment by vaishnavipamulapati** [comment]
It does look interesting! Yes, I would like to work on this.
