### ISSUE TITLE
App bar is colliding with the drawer

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#185]
![screen shot 2018-08-08 at 8 50 34 am](https://user-images.githubusercontent.com/3766511/43837990-2ef4e8ea-9ae8-11e8-8622-9a2b85b39197.png)

**Comment by helfi92** [comment]
This happens when I scroll the window horizontally.

**Comment by helfi92** [comment]
This should be a small fix. Let me know if you can't replicate this issue.

**Comment by fiennyangeln** [comment]
Yes, I still can't replicate it. I can't scroll horizontally

**Comment by helfi92** [comment]
I'll send a fix shortly.
