### ISSUE TITLE
Make the project column take less space

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#187]
The project column has a lot of unused white space. Let's find a way to make the column take less.

![screen shot 2018-08-08 at 11 37 42 am](https://user-images.githubusercontent.com/3766511/43847800-7f40acf0-9aff-11e8-8bc8-47ca08c284dd.png)

We can use the "..." when the project name is long and `title` prop for the tooltip similar to the summary column.

**Comment by fiennyangeln** [comment]
i was thinking of reducing the paddingRight of each table cell

**Comment by helfi92** [comment]
Give it a try and let's see how it looks.
