### ISSUE TITLE
Filtering is not working

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#191]
Steps to reproduce:

1. Navigate to https://codetribute.mozilla.org/projects/addons
2. Click on the "contrib: mentor assigned" tag

Actual: the table shows an empty list
Expected: the table shows items with tag "contrib: mentor assigned"

**Comment by fiennyangeln** [comment]
Its a bit weird as it works on localhost 😕  will try to reproduce the issue

**Comment by fiennyangeln** [comment]
Ah now I can reproduce it after updating my master branch..
