### ISSUE TITLE
Filter by Assigned is not working

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#195]
https://bugzilla.mozilla.org/buglist.cgi?keywords=good-first-bug%2C%20&keywords_type=allwords&list_id=14275839&resolution=---&emailtype1=notequals&query_format=advanced&emailassigned_to1=1&bug_status=NEW&bug_status=REOPENED&email1=%20nobody%40mozilla.org%20&product=Taskcluster

The link above shows two bugs with keywords 'good-first-bug'. Both are assigned but when I navigate to https://codetribute.mozilla.org/projects/taskcluster and filter by "Assigned" I get an empty list.

**Comment by fiennyangeln** [comment]
It actually appears in the unassigned ones as the status is NEW though it is assigned (currently we check on the status to set the assignee as '-')
