### ISSUE TITLE
Dissymmetry in the appearance of the website.

### ISSUE THREAD

**Issue by sonakshisaxena1** [mozilla-frontend-infra/codetribute#209]
The elements containing the text **"Bugs & Issues"** and **"I'm feeling adventurous"** are aligned in the same horizontal line on the website. 

While, there's no padding around **"Bugs & Issues"**, we can see that padding has been provided around the element **"I'm feeling adventurous."** This is causing a dissymmetry in the appearance of the website.

The following screenshots explain the above : 

1.  Dissymmetry :

 ![full](https://user-images.githubusercontent.com/24795489/44673018-f5521f80-aa47-11e8-9895-022099a3b501.png)

2.  No padding on **Bugs & Issues**:

    ![bugs](https://user-images.githubusercontent.com/24795489/44673032-000cb480-aa48-11e8-95f1-ea3ef4e10474.png)
 

3.  Padding on **I'm feeling adventurous**:

 ![padding](https://user-images.githubusercontent.com/24795489/44673075-203c7380-aa48-11e8-97e6-5ae99010eefc.png)

If suitable, then I would like to work on this issue.

**Comment by helfi92** [comment]
Good catch @sonakshisaxena1 :) Go for it!

**Comment by sonakshisaxena1** [comment]
@helfi92 I have made a PR regarding this. Please review! :)

**Comment by helfi92** [comment]
Fixed in https://github.com/mozilla-frontend-infra/codetribute/commit/128153ec1571eecb3cc9493c49099b4a79be1082.
