### ISSUE TITLE
Displeasing responsiveness on smaller screens

### ISSUE THREAD

**Issue by sonakshisaxena1** [mozilla-frontend-infra/codetribute#215]
The elements **"Bug & Issues"** and **"I'm feeling adventurous"** lack proper responsiveness. They look displeasing when seen on smaller screens.

The screenshots display the same -

- IphoneX: 

![screen shot 2018-08-29 at 10 15 56 pm](https://user-images.githubusercontent.com/24795489/44802717-18143d80-abda-11e8-912b-d6a05d99b785.png)

- Iphone 5/SE:

![screen shot 2018-08-29 at 10 15 24 pm](https://user-images.githubusercontent.com/24795489/44802718-18143d80-abda-11e8-912e-b527cd47c13c.png)

- Pixel 2:

![screen shot 2018-08-29 at 10 15 12 pm](https://user-images.githubusercontent.com/24795489/44802719-18acd400-abda-11e8-8a67-547de6e599b0.png)

Similarly, on other mobile screens like GalaxyS5 etc.

**Comment by sonakshisaxena1** [comment]
@helfi92 I would like to work on this.

**Comment by helfi92** [comment]
I assigned it to you. Thank you for taking this :)

**Comment by helfi92** [comment]
I would just add `margin: theme.spacing.unit` to the button element for small screens via theme breakpoints.

**Comment by sonakshisaxena1** [comment]
I don't think using just `margin: theme.spacing.unit` is going to solve the problem. I believe the white spacing after the text is adding to the problem. I tried it both ways - 

1. Adding `margin: theme.spacing.unit` via theme breakpoint -

![screen shot 2018-08-30 at 7 34 35 pm](https://user-images.githubusercontent.com/24795489/44856747-cc21d100-ac8b-11e8-8cde-34ec85d2e3a0.png)

2. Adding `margin: theme.spacing.unit` along with `whitespace: normal` via theme breakpoint -

![screen shot 2018-08-30 at 7 31 52 pm](https://user-images.githubusercontent.com/24795489/44856801-fd020600-ac8b-11e8-9d88-fbfec8299ec4.png)

**Comment by helfi92** [comment]
Try the following:

For small screens, modify the justifyContent of the parent element from `justifyContent: 'center'` to `justifyContent: 'flex-start'` and give the button ```margin: `${theme.spacing.unit}px 0` ```.

This should output something like:

![screen shot 2018-08-30 at 10 11 38 am](https://user-images.githubusercontent.com/3766511/44857355-a4a41780-ac3d-11e8-9f37-d007ca4be335.png)

What do you think?

**Comment by sonakshisaxena1** [comment]
Fair enough! It looks better this way :)
Should I keep `theme.breakpoints.down('sm')` or `theme.breakpoints.down(440)`.
I think the latter would be better, since most of the small screens have a width lesser than that.

**Comment by helfi92** [comment]
Let's not use hard-coded values for now. We can stick with `sm`.

**Comment by sonakshisaxena1** [comment]
Okay :)
