### ISSUE TITLE
Add icons to projects

### ISSUE THREAD

**Issue by jdm** [mozilla-frontend-infra/codetribute#222]
The project cards look kind of bare right now. Icons would help differentiate them.

**Comment by vaishnavipamulapati** [comment]
I tried doing this, but couldn't find all icons in fontawesome. Should we use something else or leave a default icon like there is for languages on the sidebar? 
![screenshot from 2018-09-17 19-27-38](https://user-images.githubusercontent.com/29792199/45627610-f8bd5180-baaf-11e8-815d-74ac229a5dce.png)

**Comment by vaishnavipamulapati** [comment]
I tried doing this, but couldn't find all icons in fontawesome. Should we use something else or leave a default icon like there is for languages on the sidebar? 
![screenshot from 2018-09-17 19-30-51](https://user-images.githubusercontent.com/29792199/45627737-34581b80-bab0-11e8-89d9-b9319d4da707.png)

**Comment by helfi92** [comment]
Those are really nice icons! Feel free to explore https://materialdesignicons.com/ as well. I'm okay using the default icons when we can't find an icon for a project :)

**Comment by fiennyangeln** [comment]
Or you can look for the project's icon svg file and put it in the project ?

**Comment by djmitche** [comment]
Maybe allowing either makes sense, in the project YAML file?

**Comment by helfi92** [comment]
Resolved in https://github.com/mozilla-frontend-infra/codetribute/commit/dc35419b168d3abdcb0fdc754fc69a0ff8f4a374.
