### ISSUE TITLE
XUL language appears to include many non-XUL tasks

### ISSUE THREAD

**Issue by jdm** [mozilla-frontend-infra/codetribute#225]
https://codetribute.mozilla.org/languages/xul shows me tasks from rust-clippy, which definitely does not include any work that requires XUL knowledge. I don't think it's searching for the right tag somehow.

**Comment by helfi92** [comment]
I assigned it to you. Thank you @fiennyangeln :)

**Comment by fiennyangeln** [comment]
I think I know why it happens

When we search for github bugs -> we first put all the repositories as the parameter and add language as parameter too. Normally, it will return the repositories that have the language. But when the language does not exist in Github language (e.g XUL) it will return all repositories 😢 

I think one easy solution is to remove github query when the language is XUL, but im not sure if its the best solution. I will try to look for other solution. Wdyt?
