### ISSUE TITLE
Find missing languages icons

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#235]
The skills drawer is missing proper icons for Perl, Rust, Shell, XML, and XUL.

![screen shot 2018-09-25 at 9 02 57 am](https://user-images.githubusercontent.com/3766511/46016078-db851600-c0a1-11e8-91a4-0f2c58a5714f.png)

For the shell icon, we could probably from https://materialdesignicons.com/.

```jsx
import ConsoleIcon from 'mdi-react/ConsoleIcon';
```

**Comment by mihhu** [comment]
Hello @helfi92 

I've found 2 libs that we could use with the following options:

- Rust: [fizzed](http://fizzed.com/oss/font-mfizz/icon-rust)

- Perl: [fizzed](http://fizzed.com/oss/font-mfizz/icon-perl), [devicons](http://vorillaz.github.io/devicons/#/singleicon/perl)

- Shell: [fizzed](http://fizzed.com/oss/font-mfizz/icon-shell), [devicons](http://vorillaz.github.io/devicons/#/singleicon/terminal) or the one you've mentioned

Would it be alright to combine them? I could create a custom icon component that takes a 'type' attribute and passes it down as a className. 

I've got nothing for XML and XUL though :( I couldn't find if they have an official logo. Do you think [fizzed](http://fizzed.com/oss/font-mfizz/icon-html) or [mdi](https://materialdesignicons.com/icon/xml) would work for XML? Maybe for XUL we could keep the default web icon.

Please let me know what you think,
Mihaela

**Comment by helfi92** [comment]
@mihhu Great find!

* Rust: [fizzed](http://fizzed.com/oss/font-mfizz/icon-rust) sounds good to me.
* Perl: [fizzed](http://fizzed.com/oss/font-mfizz/icon-perl) sounds good to me.
* Shell: You can use `import ConsoleIcon from 'mdi-react/ConsoleIcon';`

> Would it be alright to combine them?

No need to combine them. You can simply import and use them. Feel free to copy the fizzed file from https://github.com/fizzed/font-mfizz/tree/master/src/svg and include them in `src/images/languageIcons` since they don't seem to have a nice way to import the icons unless we load all of the icons.

**Comment by lashkari** [comment]
Looks like this has been sitting for a while. Mind if I take it?

My plan is to import `ConsoleIcon` as you described, but I was thinking about taking the fizzed icons and running them through [SVGOMG](https://jakearchibald.github.io/svgomg/) for optimization and then creating `PerlIcon.jsx` and `RustIcon.jsx` in `src/components/Sidebar` just to be consistent with the `HtmlIcon.jsx` and `JavaIcon.jsx` components that are already in there.

If desired, I can also make a simple SVG for XML that shows a generic document with "XML" written on it (or even "</>").

**Comment by helfi92** [comment]
ooo, completely forgot about `HtmlIcon` and `JavaIcon`. Good catch. Feel free to proceed with your plan of `RustIcon.jsx` and `PerlIcon.jsx`. SVGOMG sounds good to me!
