### ISSUE TITLE
Horyzonal scrollbar on 1920x1080

### ISSUE THREAD

**Issue by Mte90** [mozilla-frontend-infra/codetribute#242]
![immagine](https://user-images.githubusercontent.com/403283/46530846-654f9300-c89b-11e8-9dae-4e8170e27526.png)
testing with devtools seems that if I change max-width to `calc(100vw - 260px);` but is not clear to me how to patch.
Anyway this fix my issue :-)

**Comment by fiennyangeln** [comment]
@Mte90 Hi! I also see the horizontal scrollbar on my 13' laptop. We use css in js approach, so all the css for this page should be in https://github.com/mozilla-frontend-infra/codetribute/blob/master/src/views/Projects/index.jsx or https://github.com/mozilla-frontend-infra/codetribute/blob/master/src/components/Dashboard/index.jsx#L46

**Comment by Mte90** [comment]
So seems that the line that create the issue is https://github.com/mozilla-frontend-infra/codetribute/blob/master/src/views/Projects/index.jsx#L37 so maybe is not considering margins and the scrollbar on the left sidebar. 
Adding to that a 20px should fix the issue.
