### ISSUE TITLE
Allow overriding languages for issues on GitHub repos by the usage of labels

### ISSUE THREAD

**Issue by marco-c** [mozilla-frontend-infra/codetribute#246]
If I open https://codetribute.mozilla.org/languages/javascript, I see issues from the `mozilla/firefox-code-coverage-frontend` project, but I don't see issues from the `marco-c/code-coverage-reports` (even though issues from `mozilla/firefox-code-coverage-frontend` don't have a language label, issues from `marco-c/code-coverage-reports` do).

How can the language "skill" be specified for projects (or better, issues, since in several of my projects there are issues where different skills are needed)?

**Comment by fiennyangeln** [comment]
@marco-c Currently, for bugzilla hosted bug we query for `lang=js`. 

For github repositories, we first query for the most used language for each repository. Then we filter the repositories based on the result and the current query, e.g javascript, and fetch all the repositories left using the labels that are put by the project owners.

Hope it helps :)

**Comment by marco-c** [comment]
Is there a way for me to make issues from https://github.com/marco-c/code-coverage-reports/issues show up in the correct language sections?

**Comment by fiennyangeln** [comment]
I have checked that Github does not detect any primary language on that repositories.

Currently we haven't supported language labels on the query. And I will take a look at how we can possibily integrate it to the system!

**Comment by fiennyangeln** [comment]
Hi @marco-c can you try adding `lang=javascript` to those issues?

**Comment by marco-c** [comment]
I can do it for this repo, but I can't change the conventions for all repos. It would be nice to allow defining the language labels in the YAML files, like Bugsahoy did.
