### ISSUE TITLE
Add animation to the onClick event of See More button in the project page

### ISSUE THREAD

**Issue by fiennyangeln** [mozilla-frontend-infra/codetribute#249]
Now, the button works just fine. We can make the transition of the information panel smoother by using some CSS animation, e.g transformY

Or we can integrate the ExpansionPanel

**Comment by helfi92** [comment]
I think we should use a transition animation instead of an ExpansionPanel. The material UI docs has good resources for introducing transitions. https://material-ui.com/utils/transitions/#transitions.

**Comment by helfi92** [comment]
The [Collapse](https://material-ui.com/utils/transitions/#collapse) component is the one I would go with.

**Comment by fiennyangeln** [comment]
Yeah compared to changing the whole implementation to Expansion Panel I prefer Collapse too! My main concern is that it requires height though and for our project the height might be different per page.
