### ISSUE TITLE
Netlify builds failing

### ISSUE THREAD

**Issue by djmitche** [mozilla-frontend-infra/codetribute#250]
https://app.netlify.com/sites/codetribute/deploys/5bbb63cc3813f05c8220fa24
logs run from
```
10:03:56 AM: Build ready to start
...
10:43:59 AM: icon2173.2bc043e40c6a55d0413c.v1.js 2.01 kB icon2173 [emitted] icon2173
```
suggesting there's a 40-minute timeout.  Would it be possible to maybe generate fewer icons? :)

**Comment by helfi92** [comment]
Clearing the cache and redeploying seem to work.

> Would it be possible to maybe generate fewer icons?

Given that we define project icons in the yaml file, we end up dynamically importing icons. When building the project webpack has to build every single icon since it doesn't know which icon will be imported until runtime.

**Comment by fiennyangeln** [comment]
Do you guys think minifying the svg will result in better performance? @helfi92 @djmitche

**Comment by djmitche** [comment]
I suspect that minification process would take longer during the build phase.

**Comment by helfi92** [comment]
We could use data-URIs to improve performance but the security team doesn't recommend us to do that. I've opened https://github.com/mozilla-frontend-infra/codetribute/pull/253 to decrease a bit of their sizes.

**Comment by helfi92** [comment]
The servo svg file is pretty heavy :(

```bash
 292.0 KiB [##########]  servo.svg
   16.0 KiB [          ]  taskcluster.svg
   12.0 KiB [          ]  seamonkey.svg
    4.0 KiB [          ]  rust.svg
    4.0 KiB [          ]  webextensions.svg
```

**Comment by helfi92** [comment]
https://github.com/mozilla-frontend-infra/codetribute/issues/250#issuecomment-428173837 resolved the issue.
