### ISSUE TITLE
Alphabetically sorted list of projects in dropdown

### ISSUE THREAD

**Issue by ydidwania** [mozilla-frontend-infra/codetribute#255]
Right now the list of projects appear to be random (though they might not actually be). It would be much easier to browse if they were listed in the alphabetic order.
![image](https://user-images.githubusercontent.com/22861049/47256037-13ac2880-d497-11e8-875d-c9551d63f96d.png)

**Comment by helfi92** [comment]
Agreed.

**Comment by fiennyangeln** [comment]
It is better not to consider lower and upper case too, IMO

**Comment by lashkari** [comment]
I've got a working patch for this but I'm relatively new to contributing to projects like this.

Are there any coding conventions or concerns I should be aware of before submitting a pull request?

**Comment by helfi92** [comment]
Hey @lashkari, a working patch is good enough to open a pull-request :) We can iterate on it if changes are required.

**Comment by lashkari** [comment]
Sorry for the multiple pull requests. I had a formatting issue that prettier apparently didn't correct the first time.

**Comment by helfi92** [comment]
Fixed in https://github.com/mozilla-frontend-infra/codetribute/commit/85465e2aba5afaf62d2eb3718ee1ee0f114a38b8.
