### ISSUE TITLE
Migrate to Neutrino v9

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#259]
Here's the migration guide: https://master.neutrinojs.org/migration-guide/#neutrino-v8-to-v9.

**Comment by fiennyangeln** [comment]
I can try doing this 😃

**Comment by helfi92** [comment]
@fiennyangeln This is awesome! Thanks for offering your help :) For inspiration, you can also look at https://github.com/taskcluster/taskcluster-web/commit/0a187e352bf6eb97c60682ba69b4004dd5cba632 (migration of tc-web to neutrino v9).

**Comment by fiennyangeln** [comment]
can we close this one? @helfi92

**Comment by helfi92** [comment]
Indeed. This was resolved in https://github.com/mozilla-frontend-infra/codetribute/commit/0d540e37ee8d05a1025d849cebd3c2e6d43748ef.
