### ISSUE TITLE
Switch to using React.lazy

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#274]
Let's remove `react-loadable` and use `React.lazy` instead which was introduced in React v16.6.

https://reactjs.org/docs/code-splitting.html#reactlazy

For inspiration, you can look at how it's done in another repository https://github.com/taskcluster/taskcluster-web/pull/206.

**Comment by armenzg** [comment]
`react-lodable` was breaking my HMR support:
https://github.com/mozilla/bugzilla-dashboard/commit/626af8c429e6188eda3801e624f5a8161a51a3ab

**Comment by djmitche** [comment]
I think it is!  Please get started based on the above information.  Although we are not as "available" as usual right now due to work holidays, we are happy to answer questions.

**Comment by fiennyangeln** [comment]
Let's close this issue ? @helfi92
