### ISSUE TITLE
On the homepage, sometimes the page is automatically scrolled to the top

### ISSUE THREAD

**Issue by marco-c** [mozilla-frontend-infra/codetribute#277]
When I load https://codetribute.mozilla.org/ and scroll down a bit, sometimes the browser automatically scrolls back to the top.

**Comment by marco-c** [comment]
I'm thinking this is likely a bug in Firefox, related to https://bugzilla.mozilla.org/show_bug.cgi?id=1519644.

**Comment by fiennyangeln** [comment]
Thanks for clarifying @marco-c !
