### ISSUE TITLE
Update dependency date-fns to v2.0.0-alpha.27

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#285]
We use Renovate to update the dependencies of this project. However, we had  to close https://github.com/mozilla-frontend-infra/codetribute/pull/273 since it had breaking changes. We would need a manual update of this package. The [release notes](https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136) will be useful for updating the package.

**Comment by fiennyangeln** [comment]
thanks hassan for opening the issue! should have done that 😬
