### ISSUE TITLE
Add links to initiatives Mozilla is apart of

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#307]
We should probably add a link to Outreachy and Google Summer of Code somewhere on the homepage. Maybe somewhere in the bottom of the skills section:

<img width="242" alt="Screen Shot 2019-06-19 at 3 01 50 PM" src="https://user-images.githubusercontent.com/3766511/59804452-351e1800-92a3-11e9-83a3-9902731aa142.png">

**Comment by Patil2099** [comment]
@helfi92  Can I work on this?

**Comment by helfi92** [comment]
Go for it :)

**Comment by Patil2099** [comment]
Do I have to make an icon or you will provide me with one and where should these point to? 
![MIF](https://user-images.githubusercontent.com/35653876/62837093-e41a1700-bc88-11e9-96c4-9a5bfd9173af.png)

**Comment by helfi92** [comment]
> Do I have to make an icon or you will provide me with one and where should these point to?

I don't think we need an icon. Outreachy and Google Summer of Code are not skills so perhaps we could just put the links at the bottom of the drawer. Something like:

![Screen Shot 2019-08-11 at 1 29 16 PM](https://user-images.githubusercontent.com/3766511/62837305-105b7680-bc3c-11e9-8fcc-d98b1584c1de.png)

**Comment by nidhirpatil** [comment]
@helfi92 Hey!
Can I work on this?

**Comment by helfi92** [comment]
Hey @nidhirpatil. This issue is actually assigned to @Patil2099. https://github.com/mozilla-frontend-infra/codetribute/issues/248 is free to grab. If you are interested, then comment directly on the issue and feel free to start working on the issue.
