### ISSUE TITLE
Handle mentored bugs for bugzilla

### ISSUE THREAD

**Issue by fiennyangeln** [mozilla-frontend-infra/codetribute#32]
As of now, the bugs we are fetching from bugzilla are those labeled 'good-first-bug' as its tag, when I check on a few website linking to bugsahoy, most of the site mentioned that BugsAhoy are meant for mentored bugs so i think we may need to add capabilities for mentored bugs
TODO: find appropriate query to query mentored bugs

**Comment by djmitche** [comment]
http://bluesock.org/~willkg/blog/mozilla/mentorable_bugs2.html might help
