### ISSUE TITLE
Issue not supposed to show up

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#338]
STR:

1. Navigate to https://codetribute.mozilla.org/projects/taskcluster?sortBy%3DLast%2520Updated%26sortDirection%3Ddesc

2. Search for "[UI] remove search pattern for clients viewer"

Actual:

<img width="1650" alt="Screen Shot 2019-09-20 at 10 54 41 AM" src="https://user-images.githubusercontent.com/3766511/65336840-132f7c80-db95-11e9-8ebb-4271d3375bc9.png">

Expected: "[UI] remove search pattern for clients viewer" does not show up in the UI since that issue was closed a while back.

**Comment by arshadkazmi42** [comment]
@helfi92 Is this still available? I can take this up.

**Comment by helfi92** [comment]
Hey @arshadkazmi42 👋 Go for it!

**Comment by fiennyangeln** [comment]
Trying to investigate a little bit and I couldn't find the reason so I posted [here](https://github.community/t5/GitHub-API-Development-and/Closed-issue-appeared-despite-the-state-open-filter/td-p/37600)

**Comment by arshadkazmi42** [comment]
@helfi92 I am not finding much time to look into this. You can unassign me let it open for other contributors. I will ping here if I am going to work on it again.  Thanks

**Comment by fiennyangeln** [comment]
@helfi92 I think we can close this issue. The Github community forum has responded to my [query](https://github.community/t5/GitHub-API-Development-and/Closed-issue-appeared-despite-the-state-open-filter/td-p/37600) and it seems that the cause is its database glitch. Wdyt?

**Comment by helfi92** [comment]
@fiennyangeln Thanks for asking in the GitHub community forum! We can definitely close this issue.
