### ISSUE TITLE
Add Kotlin to the list of languages

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla-frontend-infra/codetribute#340]
Many Mozilla projects have started using Kotlin as the main language.
Examples:
https://github.com/mozilla-mobile/focus-android
https://github.com/mozilla-mobile/android-components
https://github.com/mozilla-mobile/firefox-tv

If this is approved, I can pick this up

**Comment by helfi92** [comment]
I think that makes sense. Thanks for offering your help! Go for it.
