### ISSUE TITLE
Add Fenix to the list of projects

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla-frontend-infra/codetribute#345]
Fenix can be found at https://github.com/mozilla-mobile/fenix and has a lot of open issues with proper tags.

I can make a PR for this. It will also serve as verification for #340

**Comment by SubhrajyotiSen** [comment]
Additionally, even https://github.com/mozilla-mobile/android-components can be added. Should I open a new PR for this? Or can it be tracked on this issue?

**Comment by djmitche** [comment]
Combining the two is fine.

**Comment by SubhrajyotiSen** [comment]
Can I make a PR for the same?

**Comment by djmitche** [comment]
Absolutely!

**Comment by helfi92** [comment]
Resolved in https://github.com/mozilla-frontend-infra/codetribute/commit/07642b246b0b2f45903c1a858214ff95e15cad83.
