### ISSUE TITLE
Allow projects to merge multiple modules into 1 item

### ISSUE THREAD

**Issue by nchevobbe** [mozilla-frontend-infra/codetribute#383]
_This is a DevTools specific request, but maybe other projects would be interested._

In DevTools, the Inspector panel is represented by multiple modules, which can be confusing for newcomers

<img width="300" alt="image" src="https://user-images.githubusercontent.com/578107/75148153-3d1a3b80-56ff-11ea-8b4e-6d4d20c28b1d.png">

It would be nice if we could maintain a list of the modules that we'd like to merge into a single "main" module.

**Comment by djmitche** [comment]
Those multiple modules are different Bugzilla components, so the request here is to be able to display multiple components as a single item on this menu.

**Comment by nchevobbe** [comment]
> Those multiple modules are different Bugzilla components, so the request here is to be able to display multiple components as a single item on this menu.

exactly

**Comment by captainbrosset** [comment]
For information, the mapping we currently use in another tool (https://bugs.firefox-dev.tools) for this is the following one:

https://github.com/firefox-devtools/devtools-bug-finder/blob/gh-pages/components.js#L3

**Comment by fiennyangeln** [comment]
I don't think it is hard to implement the mapping between the components, but we may need to decide:
1. Should we make it a must for a product to specify all the components and their mapping if that product needs the label mapping in at least one of the components?
2. What should happen when there are no bugs for all the component grouped together, should we still show the label? Since currently the component names are derived from the list of bugs.. So if the component 'Inspector' has no bug currently then it won't show up.
3. How should the new YAML file look like?

One possible mapping would be:
```yaml
name: Devtools
icon: bug
products:
 - DevTools: [
 'Administration', 
 {'label': 'Inspector', 
 'components': ["Inspector",
                 "Inspector:\ Animations",
                 "Inspector:\ Changes",
                 "Inspector:\ Computed",
                 "Inspector:\ Fonts",
                 "Inspector:\ Layout",
                 "Inspector:\ Rules",
                 "Style Editor",
                 "Responsive Design Mode"]
  },
 'Bug Import/Export & Moving',
 'Bugzilla-General', 
 'bugzilla.org', 
 'Creating/Changing Bugs',
 'Documentation',
 'Email Notifications',
 'Extensions',
 'QA Test Scripts',
 'Query/Bug Lists',
 'Testing Suite',
 'User Accounts',
 'User Interface',
 'WebService',
 'Whining']

```

**Comment by djmitche** [comment]
That format does limit us to only combining components in a single product, if I understand correctly.

**Comment by fiennyangeln** [comment]
Thanks, Dustin! That's true I didn't think of it before. 

```yaml
name: Devtools
icon: bug
products:
 - label: 'Inspector'
   products:
      - DevTools: ['Inspector', 'Inspector:Animation']
      - Core: ['Graphics']
 - Devtools: ['Administration']
 - Bugzilla: ['Attachment & Request']
```

How about something like the above?

**Comment by djmitche** [comment]
I like that -- very readable!

**Comment by helfi92** [comment]
@nchevobbe This should now be possible. Thank you @fiennyangeln for this awesome feature!

**Comment by nchevobbe** [comment]
awesome, thanks @fiennyangeln !
