### ISSUE TITLE
Add Icon Color Consistency

### ISSUE THREAD

**Issue by zacnomore** [mozilla-frontend-infra/codetribute#407]
Currently some of the icons are the same colors and others are just the colors natural to their normal context.
I suggest making them all use the same color scheme, the icon colors are not especially useful for scanning the categories IMO and I believe it looks cleaner when consistent.

Before:
![Screen Shot 2020-07-30 at 11 51 12 AM](https://user-images.githubusercontent.com/5839548/88945102-901e8e80-d25b-11ea-99b8-8be1fed858bd.png)

After:
![Screen Shot 2020-07-30 at 11 51 56 AM](https://user-images.githubusercontent.com/5839548/88945098-8eed6180-d25b-11ea-9e22-ae891dce7fc4.png)

**Comment by Neilblaze** [comment]
Assign me this issue please @zacnomore

**Comment by Neilblaze** [comment]
Assign me this issue please @zacnomore

**Comment by Neilblaze** [comment]
I think, adding this `class="mdi-icon" fill="currentColor"` to the svg's with their natural colours, will fix the issue.

**Comment by zacnomore** [comment]
@Neilblaze I don't own or maintain this repo, the issue is a suggestion

**Comment by djmitche** [comment]
Have at it, @Neilblaze!

**Comment by Neilblaze** [comment]
@djmitche please review PR #408
