### ISSUE TITLE
Website broken 

### ISSUE THREAD

**Issue by soniasingla** [mozilla-frontend-infra/codetribute#418]
The homepage is working fine but when we click on any `project` and `skills` section (ex: https://codetribute.mozilla.org/projects/ff) it's not working, can anyone please check this?

**Comment by djmitche** [comment]
Huh, looks like an update broke it :(

**Comment by djmitche** [comment]
Fixed in #419.

**Comment by djmitche** [comment]
New issue #420 for the actual upgrade.

**Comment by soniasingla** [comment]
@djmitche it's working now 👍 

But it seems to be slower than before !!

**Comment by djmitche** [comment]
That may be to do with bugzilla or github.  The site itself doesn't do anything that would have good or bad performance.
