### ISSUE TITLE
Thunderbird project still mentions IRC comms

### ISSUE THREAD

**Issue by wsmwk** [mozilla-frontend-infra/codetribute#442]
https://codetribute.mozilla.org/projects/thunderbird still mentions IRC .  (actually so does https://codetribute.mozilla.org/projects/ff )

> Our IRC support channel is #thunderbird, and our development channel is #maildev at irc.mozilla.org You can find information on how to contribute to Thunderbird at https://thunderbird.net/get-involved

I think we could replace all that and just point to https://www.thunderbird.net/en-US/get-involved/#communication

**Comment by wsmwk** [comment]
https://codetribute.mozilla.org/projects/calendar also needs a similar update

**Comment by djmitche** [comment]
Thanks!  Can you make a PR? The data is under `src/data`.

**Comment by djmitche** [comment]
(and note that at the moment deployments are broken, so the fix won't show up right away -- but we can get a PR landed and once deployment works, it will show up)
