### ISSUE TITLE
Change the desc of the website for card generated via apps 

### ISSUE THREAD

**Issue by championshuttler** [mozilla-frontend-infra/codetribute#502]
https://github.com/mozilla-frontend-infra/codetribute/blob/6ec8a9e4d34338a8242074ae1600dc5400bb5f2e/public/index.html#L10

![image](https://user-images.githubusercontent.com/22130317/113850386-08106180-97b8-11eb-8767-2d2e412eb11c.png)
 it looks like this rn in matrix so its better to change the description to something interesting 

`Tool to help contributors find interesting good first bugs bugs to work on` 

WDYT @djmitche

**Comment by djmitche** [comment]
Good spot -- yes, please update!  This is something I missed in removing Neutrino from the app, I think.
