### ISSUE TITLE
Have the project introduction be in a panel

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#53]
It would be neat to be able to hide the project introduction if a user does not want to be bothered by it. Material UI offers the [expansion panel](https://material-ui.com/demos/expansion-panels/) which we could make use of it. When a user enters the page, we could have the panel expanded by default.

**Comment by fiennyangeln** [comment]
@helfi92 I am thinking of using something like this https://github.com/njvack/markdown-to-json then display each header in a different expansion panel. but im not sure how to handle nested description (like h1, then inside got h2, then inside got h3). wdyt?

**Comment by helfi92** [comment]
This might be good to have but I'm not sure we should do this in the beginning. Let's take the simple approach of dumping everything in the panel and then we can enhance it in a future iteration.

**Comment by fiennyangeln** [comment]
ok :+1:
