### ISSUE TITLE
Generate a new PAT

### ISSUE THREAD

**Issue by matt-boris** [mozilla-frontend-infra/codetribute#548]
Similar to #469 but this time is to provide additional security benefits. Read GitHub's blog post here https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

**Comment by matt-boris** [comment]
I've generated, just need to hand it off to ops.

**Comment by petemoore** [comment]
I've also created:
  * [Bug 1756752: Codetribute broken (prod) and needs updated github access token)](https://bugzi.la/1756752)

**Comment by matt-boris** [comment]
Got netlify access to update the github personal access token and redeployed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1756752 is now closed.
