### ISSUE TITLE
Rust project is not opened

### ISSUE THREAD

**Issue by junngo** [mozilla-frontend-infra/codetribute#557]
Hi :)
When I enter the Rust project in codetribute, the Rust project is not opened.

![Screenshot from 2022-04-07 01-04-33](https://user-images.githubusercontent.com/29684524/162018646-5c73683e-f753-4380-96a0-abf571ceebb0.png)

URL) https://codetribute.mozilla.org/projects/rust

**Comment by djmitche** [comment]
After some debugging, it appears to be because the query matches a PR, and PRs don't have a `repository` property.

![image](https://user-images.githubusercontent.com/28673/162552430-d05badc8-eddd-4af8-98b7-0b7be17078b9.png)
