### ISSUE TITLE
The icon for the Bots section does not match the selected one

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla-frontend-infra/codetribute#596]
The selected icon for the Bots section is [robot](https://materialdesignicons.com/icon/robot):

https://github.com/mozilla-frontend-infra/codetribute/blob/d3e4ce38ee550878d712917cf91d545de26661c7/src/data/bots.yml#L3

However, the icon that appears on the website is [web](https://materialdesignicons.com/icon/web):

<img width="355" alt="image" src="https://user-images.githubusercontent.com/4151357/210816655-00134ff3-3788-4258-864d-1f73965fd92b.png">

**Comment by lotas** [comment]
Found out that icons are hardcoded here: https://github.com/mozilla-frontend-infra/codetribute/blob/fb025b354d674f9319f60a78e8f4ba35ce611cda/src/components/ProjectIcon/index.jsx

**Comment by suhaibmujahid** [comment]
Thank you, @lotas! I will open a PR to fix it.

**Comment by lotas** [comment]
Awesome, thank you!
