### ISSUE TITLE
Project summary takes a lot of horizontal space in the table

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#74]
The project summary sometimes takes a lot of horizontal space. We should perhaps add a maximum width and `...` at the end to show the text is cut. To see the full summary, we could use a tooltip.

_Example: Bug 1135584 takes a lot of horizontal space pushing subsequent columns further_
![screen shot 2018-07-04 at 9 37 53 am](https://user-images.githubusercontent.com/3766511/42280188-ff3e55f4-7f6d-11e8-9236-073dad9a626c.png)

**Comment by fiennyangeln** [comment]
@helfi92 can we use Drawer instead -- together with the bug information?

**Comment by helfi92** [comment]
Having a tooltip doesn't mean we shouldn't use a Drawer to show more information about the bug/issue. Including a tooltip is as simple as adding the `title={summary}` prop. We can integrate the drawer in the other PR.
