### ISSUE TITLE
Remove text wrapping from Last Updated

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/codetribute#93]
![screen shot 2018-07-11 at 11 04 25 am](https://user-images.githubusercontent.com/3766511/42581220-406a8b1a-84fa-11e8-856e-58b580c2efb7.png)

**Comment by fiennyangeln** [comment]
@helfi92 does it mean making it like the summary? no wrap?

**Comment by helfi92** [comment]
Yes, just like the summary. No need to take care of adding `...` at the end however because it will never be too long and it's also the last column.
